export const VIEW = {
    MAIN_MENU: 'MAIN_MENU',
    OPTIONS_MENU: 'OPTIONS_MENU',
    GAME_VIEW: 'GAME_VIEW',
    END_GAME_VICTORY: 'END_GAME_VICTORY',
    END_GAME_LOSS: 'END_GAME_LOSS',
    LOADING: 'LOADING',
    ERROR: 'ERROR',
};
