import { ROOM_TYPES } from './constants';

export const maps = [
    'map',
];

export const map = {
    config: {
        rows: 4,
        columns: 4,
    },
    schema: {
        1: {
            roomId: 1,
            roomType: ROOM_TYPES.ENTRANCE,
            north: 0,
            east: 2,
            south: 0,
            west: 0,
        },
        2: {
            roomId: 2,
            roomType: ROOM_TYPES.DEFAULT,
            north: 0,
            east: 0,
            south: 6,
            west: 1,
        },
        3: {
            roomId: 3,
            roomType: ROOM_TYPES.DEFAULT,
            north: 0,
            east: 0,
            south: 0,
            west: 0,
        },
        4: {
            roomId: 4,
            roomType: ROOM_TYPES.DEFAULT,
            north: 0,
            east: 0,
            south: 7,
            west: 0,
        },
        5: {
            roomId: 5,
            roomType: ROOM_TYPES.TREASURE,
            north: 0,
            east: 6,
            south: 0,
            west: 0,
        },
        6: {
            roomId: 6,
            roomType: ROOM_TYPES.ENEMY,
            north: 2,
            east: 7,
            south: 10,
            west: 5,
        },
        7: {
            roomId: 7,
            roomType: ROOM_TYPES.ENEMY,
            north: 0,
            east: 6,
            south: 0,
            west: 8,
        },
        8: {
            roomId: 8,
            roomType: ROOM_TYPES.TREASURE,
            north: 4,
            east: 0,
            south: 12,
            west: 7,
        },
        9: {
            roomId: 9,
            roomType: ROOM_TYPES.DEFAULT,
            north: 0,
            east: 10,
            south: 13,
            west: 0,
        },
        10: {
            roomId: 10,
            roomType: ROOM_TYPES.TREASURE,
            north: 6,
            east: 11,
            south: 0,
            west: 9,
        },
        11: {
            roomId: 11,
            roomType: ROOM_TYPES.ENEMY,
            north: 0,
            east: 0,
            south: 15,
            west: 10,
        },
        12: {
            roomId: 12,
            roomType: ROOM_TYPES.EXIT,
            north: 8,
            east: 0,
            south: 16,
            west: 0,
        },
        13: {
            roomId: 13,
            roomType: ROOM_TYPES.ENTRANCE,
            north: 9,
            east: 0,
            south: 0,
            west: 0,
        },
        14: {
            roomId: 14,
            roomType: ROOM_TYPES.DEFAULT,
            north: 0,
            east: 0,
            south: 0,
            west: 0,
        },
        15: {
            roomId: 15,
            roomType: ROOM_TYPES.ENEMY,
            north: 11,
            east: 16,
            south: 0,
            west: 0,
        },
        16: {
            roomId: 16,
            roomType: ROOM_TYPES.ENEMY,
            north: 12,
            east: 0,
            south: 0,
            west: 15,
        },
    },
};
